version: "3"

services:

  api:
    build: ./api
    ports:
      - '3001:3001'
    restart: always
    container_name: api

  app:
    build: ./app
    ports:
      - '3000:3000'
    restart: always
    container_name: app
